import React, { useState, useMemo } from "react";
import { Info } from "lucide-react";
import { Slider } from "../Slider";
import { MetricCard } from "../MetricCard";
import { Tooltip } from "../Tooltip";
import { calculateLBO } from "../../utils/lbo";
import {
  formatMillions,
  formatPercent,
  formatMultiple,
  formatIRR,
} from "../../utils/formatting";
import type { LBOInputs } from "../../types/fund";

const DEFAULT_LBO: LBOInputs = {
  entryEBITDA: 50,
  entryMultiple: 12,
  debtPercent: 0.6,
  interestRate: 0.075,
  ebitdaGrowthRate: 0.1,
  exitMultiple: 14,
  holdYears: 5,
  fcfConversion: 0.55,
  mandatoryAmortization: 0.05,
};

const EXIT_MULTS = [8, 10, 12, 14, 16, 18, 20];
const GROWTH_RATES = [-0.05, 0, 0.05, 0.1, 0.15, 0.2];

function moicColor(moic: number): string {
  if (moic >= 3) return "#34D399";
  if (moic >= 2) return "#818CF8";
  if (moic >= 1.5) return "#FCD34D";
  if (moic >= 1) return "#9CA3AF";
  return "#F87171";
}

export function LBOTab() {
  const [lbo, setLBO] = useState<LBOInputs>(DEFAULT_LBO);

  const result = useMemo(() => calculateLBO(lbo), [lbo]);

  const set = <K extends keyof LBOInputs>(k: K, v: LBOInputs[K]) =>
    setLBO((prev) => ({ ...prev, [k]: v }));

  const vc = result.valueCreation;
  const vcTotal =
    Math.abs(vc.ebitdaGrowth) +
    Math.abs(vc.multipleExpansion) +
    Math.abs(vc.debtPaydown);

  return (
    <div className="max-w-7xl mx-auto px-6 py-8 space-y-6">
      {/* Educational callout */}
      <div
        className="flex gap-3 p-4 rounded-xl"
        style={{
          background: "rgba(245,158,11,0.08)",
          border: "1px solid rgba(245,158,11,0.2)",
        }}
      >
        <Info
          size={16}
          className="flex-shrink-0 mt-0.5"
          style={{ color: "#F59E0B" }}
        />
        <div className="text-sm text-[#9CA3AF] leading-relaxed">
          <strong style={{ color: "#F59E0B" }}>Leveraged Buyout (LBO)</strong>{" "}
          returns come from three sources:{" "}
          <Tooltip
            term="EBITDA Growth"
            definition="Organic revenue growth and/or margin expansion increase earnings, which drive a higher EV at exit"
          >
            EBITDA growth
          </Tooltip>
          ,{" "}
          <Tooltip
            term="Multiple Expansion"
            definition="Exiting at a higher EV/EBITDA multiple than the entry multiple (market re-rating, improved business quality)"
          >
            multiple expansion
          </Tooltip>
          , and{" "}
          <Tooltip
            term="Debt Paydown"
            definition="Free cash flow generated by the business reduces debt, converting enterprise value to equity value"
          >
            debt paydown
          </Tooltip>
          . High leverage amplifies equity returns but increases default risk if
          EBITDA declines.
        </div>
      </div>

      {/* Entry Parameters */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div
          className="rounded-xl p-5"
          style={{ background: "#111827", border: "1px solid #374151" }}
        >
          <h3 className="text-sm font-semibold text-[#F9FAFB] mb-4">
            Entry & Structure
          </h3>
          <div className="grid grid-cols-2 gap-6">
            <Slider
              label="Entry EBITDA"
              value={lbo.entryEBITDA}
              min={5}
              max={500}
              step={5}
              format={(v) => formatMillions(v)}
              onChange={(v) => set("entryEBITDA", v)}
            />
            <Slider
              label="Entry EV/EBITDA"
              value={lbo.entryMultiple}
              min={4}
              max={25}
              step={0.5}
              format={(v) => `${v.toFixed(1)}x`}
              onChange={(v) => set("entryMultiple", v)}
            />
            <Slider
              label="Debt / EV"
              value={lbo.debtPercent * 100}
              min={20}
              max={80}
              step={5}
              format={(v) => `${v.toFixed(0)}%`}
              onChange={(v) => set("debtPercent", v / 100)}
            />
            <Slider
              label="Interest Rate"
              value={lbo.interestRate * 100}
              min={3}
              max={15}
              step={0.25}
              format={(v) => `${v.toFixed(2)}%`}
              onChange={(v) => set("interestRate", v / 100)}
            />
            <Slider
              label="Mandatory Amort"
              value={lbo.mandatoryAmortization * 100}
              min={0}
              max={20}
              step={1}
              format={(v) => `${v.toFixed(0)}% / yr`}
              onChange={(v) => set("mandatoryAmortization", v / 100)}
            />
            <Slider
              label="FCF Conversion"
              value={lbo.fcfConversion * 100}
              min={20}
              max={90}
              step={5}
              format={(v) => `${v.toFixed(0)}%`}
              onChange={(v) => set("fcfConversion", v / 100)}
            />
          </div>
        </div>

        <div
          className="rounded-xl p-5"
          style={{ background: "#111827", border: "1px solid #374151" }}
        >
          <h3 className="text-sm font-semibold text-[#F9FAFB] mb-4">
            Exit Assumptions
          </h3>
          <div className="grid grid-cols-2 gap-6">
            <Slider
              label="EBITDA Growth / yr"
              value={lbo.ebitdaGrowthRate * 100}
              min={-10}
              max={30}
              step={1}
              format={(v) => `${v.toFixed(0)}%`}
              onChange={(v) => set("ebitdaGrowthRate", v / 100)}
            />
            <Slider
              label="Exit EV/EBITDA"
              value={lbo.exitMultiple}
              min={4}
              max={25}
              step={0.5}
              format={(v) => `${v.toFixed(1)}x`}
              onChange={(v) => set("exitMultiple", v)}
            />
            <Slider
              label="Hold Period"
              value={lbo.holdYears}
              min={2}
              max={10}
              step={1}
              format={(v) => `${v} yr`}
              onChange={(v) => set("holdYears", v)}
            />
          </div>

          {/* Entry vs Exit summary */}
          <div className="mt-5 grid grid-cols-2 gap-3">
            {[
              {
                label: "Entry EV",
                value: formatMillions(result.entryEV),
                sub: `${lbo.entryMultiple.toFixed(1)}x EBITDA`,
                color: "#6B7280",
              },
              {
                label: "Exit EV",
                value: formatMillions(result.exitEV),
                sub: `${lbo.exitMultiple.toFixed(1)}x EBITDA`,
                color: "#34D399",
              },
              {
                label: "Entry Equity",
                value: formatMillions(result.entryEquity),
                sub: `${((1 - lbo.debtPercent) * 100).toFixed(0)}% of EV`,
                color: "#818CF8",
              },
              {
                label: "Exit Equity",
                value: formatMillions(result.exitEquity),
                sub: `After debt repayment`,
                color: "#6EE7B7",
              },
            ].map((item) => (
              <div
                key={item.label}
                className="rounded-lg p-3"
                style={{ background: "#0A0F1C", border: "1px solid #1F2937" }}
              >
                <div className="text-xs" style={{ color: "#6B7280" }}>
                  {item.label}
                </div>
                <div
                  className="text-base font-bold mt-0.5"
                  style={{ color: item.color }}
                >
                  {item.value}
                </div>
                <div className="text-xs mt-0.5" style={{ color: "#4B5563" }}>
                  {item.sub}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Key Metrics */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <MetricCard
          label="Gross MOIC"
          value={formatMultiple(result.grossMOIC)}
          status={
            result.grossMOIC >= 3
              ? "positive"
              : result.grossMOIC >= 2
                ? "neutral"
                : "negative"
          }
          description={`${lbo.holdYears}-year hold`}
        />
        <MetricCard
          label="Gross IRR"
          value={formatIRR(result.grossIRR)}
          status={
            result.grossIRR !== null && result.grossIRR > 0.2
              ? "positive"
              : result.grossIRR !== null && result.grossIRR > 0.12
                ? "neutral"
                : "negative"
          }
          description="Annualized equity return"
        />
        <MetricCard
          label="Entry Debt / EBITDA"
          value={`${(result.entryDebt / lbo.entryEBITDA).toFixed(1)}x`}
          status={
            result.entryDebt / lbo.entryEBITDA <= 5
              ? "positive"
              : result.entryDebt / lbo.entryEBITDA <= 7
                ? "neutral"
                : "negative"
          }
          description="Leverage at close"
        />
        <MetricCard
          label="Exit Debt / EBITDA"
          value={`${result.debtSchedule.find((d) => d.year === lbo.holdYears)?.debtToEBITDA.toFixed(1) ?? "—"}x`}
          status="positive"
          description="Leverage at exit"
        />
      </div>

      {/* Value Creation Bridge */}
      <div
        className="rounded-xl p-5"
        style={{ background: "#111827", border: "1px solid #374151" }}
      >
        <h3 className="text-sm font-semibold text-[#F9FAFB] mb-1">
          Value Creation Bridge
        </h3>
        <p className="text-xs text-[#6B7280] mb-4">
          Equity gain of {formatMillions(vc.total)} broken down by source
        </p>
        <div className="space-y-3">
          {[
            {
              label: "EBITDA Growth",
              value: vc.ebitdaGrowth,
              color: "#34D399",
              description: `Earnings grew from ${formatMillions(lbo.entryEBITDA)} to ${formatMillions(lbo.entryEBITDA * Math.pow(1 + lbo.ebitdaGrowthRate, lbo.holdYears))} at entry multiple`,
            },
            {
              label: "Multiple Expansion",
              value: vc.multipleExpansion,
              color: "#818CF8",
              description: `Exit at ${lbo.exitMultiple.toFixed(1)}x vs entry at ${lbo.entryMultiple.toFixed(1)}x`,
            },
            {
              label: "Debt Paydown",
              value: vc.debtPaydown,
              color: "#6EE7B7",
              description: `Debt reduced from ${formatMillions(result.entryDebt)} to ${formatMillions(result.exitDebt)}`,
            },
          ].map((item) => {
            const pct = vcTotal > 0 ? Math.abs(item.value) / vcTotal : 0;
            const isNeg = item.value < 0;
            return (
              <div key={item.label} className="space-y-1">
                <div className="flex justify-between items-center text-xs">
                  <div>
                    <span
                      style={{
                        color: isNeg ? "#F87171" : item.color,
                        fontWeight: 600,
                      }}
                    >
                      {item.label}
                    </span>
                    <span className="ml-2" style={{ color: "#4B5563" }}>
                      {item.description}
                    </span>
                  </div>
                  <span
                    style={{
                      color: isNeg ? "#F87171" : item.color,
                      fontWeight: 700,
                    }}
                  >
                    {isNeg ? "-" : "+"}
                    {formatMillions(Math.abs(item.value))}
                  </span>
                </div>
                <div
                  className="w-full rounded-full h-2.5"
                  style={{ background: "#1F2937" }}
                >
                  <div
                    className="h-2.5 rounded-full transition-all duration-500"
                    style={{
                      width: `${pct * 100}%`,
                      background: isNeg ? "#F87171" : item.color,
                    }}
                  />
                </div>
                <div className="text-xs" style={{ color: "#4B5563" }}>
                  {(pct * 100).toFixed(0)}% of total value creation
                </div>
              </div>
            );
          })}
        </div>

        {/* Bridge totals */}
        <div className="mt-4 pt-4 border-t border-[#1F2937] flex justify-between text-sm">
          <span style={{ color: "#9CA3AF" }}>Entry Equity</span>
          <span style={{ color: "#6B7280" }}>
            {formatMillions(result.entryEquity)}
          </span>
        </div>
        <div className="flex justify-between text-sm">
          <span style={{ color: "#9CA3AF" }}>+ Value Created</span>
          <span style={{ color: "#34D399" }}>+{formatMillions(vc.total)}</span>
        </div>
        <div className="flex justify-between text-sm font-bold border-t border-[#374151] pt-2 mt-1">
          <span style={{ color: "#F9FAFB" }}>= Exit Equity</span>
          <span style={{ color: "#34D399" }}>
            {formatMillions(result.exitEquity)}
          </span>
        </div>
      </div>

      {/* Debt Schedule */}
      <div
        className="rounded-xl p-5"
        style={{ background: "#111827", border: "1px solid #374151" }}
      >
        <h3 className="text-sm font-semibold text-[#F9FAFB] mb-4">
          Debt Amortization Schedule
        </h3>
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr style={{ borderBottom: "1px solid #374151" }}>
                {[
                  "Year",
                  "Beg. Debt",
                  "EBITDA",
                  "Interest",
                  "Amortization",
                  "End Debt",
                  "D/EBITDA",
                  "Equity",
                  "MOIC",
                ].map((h) => (
                  <th
                    key={h}
                    className="pb-2 text-right first:text-left"
                    style={{
                      color: "#6B7280",
                      fontWeight: 600,
                      paddingRight: 12,
                    }}
                  >
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {result.debtSchedule.slice(0, lbo.holdYears).map((row) => (
                <tr
                  key={row.year}
                  style={{ borderBottom: "1px solid #1F2937" }}
                >
                  {[
                    { v: `Year ${row.year}`, left: true },
                    { v: formatMillions(row.beginningDebt) },
                    { v: formatMillions(row.ebitda) },
                    {
                      v: `(${formatMillions(row.interest)})`,
                      color: "#F87171",
                    },
                    {
                      v: `(${formatMillions(row.amortization)})`,
                      color: "#FCD34D",
                    },
                    { v: formatMillions(row.endingDebt) },
                    {
                      v: `${row.debtToEBITDA.toFixed(1)}x`,
                      color:
                        row.debtToEBITDA <= 5
                          ? "#34D399"
                          : row.debtToEBITDA <= 7
                            ? "#FCD34D"
                            : "#F87171",
                    },
                    { v: formatMillions(row.equity), color: "#818CF8" },
                    {
                      v: `${row.moic.toFixed(2)}x`,
                      color: moicColor(row.moic),
                    },
                  ].map((cell, ci) => (
                    <td
                      key={ci}
                      className={`py-2 ${cell.left ? "text-left" : "text-right"}`}
                      style={{
                        color: cell.color ?? "#D1D5DB",
                        paddingRight: 12,
                      }}
                    >
                      {cell.v}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Sensitivity Table */}
      <div
        className="rounded-xl p-5"
        style={{ background: "#111827", border: "1px solid #374151" }}
      >
        <h3 className="text-sm font-semibold text-[#F9FAFB] mb-1">
          MOIC Sensitivity
        </h3>
        <p className="text-xs text-[#6B7280] mb-4">
          Exit multiple (rows) × EBITDA growth rate (columns) — hold period:{" "}
          {lbo.holdYears} years
        </p>
        <div className="overflow-x-auto">
          <table className="text-xs">
            <thead>
              <tr>
                <th
                  className="pb-2 pr-3 text-left"
                  style={{ color: "#6B7280" }}
                >
                  Exit × \ Growth
                </th>
                {GROWTH_RATES.map((gr) => (
                  <th
                    key={gr}
                    className="pb-2 px-3 text-center"
                    style={{ color: "#6B7280" }}
                  >
                    {(gr * 100).toFixed(0)}%
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {EXIT_MULTS.map((em) => (
                <tr key={em}>
                  <td
                    className="py-1.5 pr-3 font-semibold"
                    style={{ color: "#9CA3AF" }}
                  >
                    {em}x
                  </td>
                  {GROWTH_RATES.map((gr) => {
                    const cell = result.sensitivityGrid.find(
                      (c) =>
                        c.exitMult === em &&
                        Math.abs(c.growthRate - gr) < 0.001,
                    );
                    const m = cell?.moic ?? 0;
                    const isTarget =
                      em === lbo.exitMultiple &&
                      Math.abs(gr - lbo.ebitdaGrowthRate) < 0.001;
                    return (
                      <td
                        key={gr}
                        className="py-1.5 px-3 text-center rounded"
                        style={{
                          color: moicColor(m),
                          fontWeight: isTarget ? 800 : 500,
                          background: isTarget
                            ? "rgba(99,102,241,0.15)"
                            : "transparent",
                          border: isTarget
                            ? "1px solid rgba(99,102,241,0.4)"
                            : "1px solid transparent",
                        }}
                      >
                        {m.toFixed(2)}x
                      </td>
                    );
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="mt-3 flex gap-4 text-xs">
          {[
            { color: "#34D399", label: "≥3x" },
            { color: "#818CF8", label: "2–3x" },
            { color: "#FCD34D", label: "1.5–2x" },
            { color: "#9CA3AF", label: "1–1.5x" },
            { color: "#F87171", label: "<1x (loss)" },
          ].map((item) => (
            <span
              key={item.label}
              className="flex items-center gap-1"
              style={{ color: item.color }}
            >
              <span
                style={{
                  width: 8,
                  height: 8,
                  borderRadius: 2,
                  background: item.color,
                  display: "inline-block",
                }}
              />
              {item.label}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}
