import React, { useState, useMemo } from "react";
import { Info } from "lucide-react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip as RechartTooltip,
  Cell,
  ResponsiveContainer,
  ReferenceLine,
} from "recharts";
import { Slider } from "../Slider";
import { MetricCard } from "../MetricCard";
import { Tooltip } from "../Tooltip";
import { calculateLBO } from "../../utils/lbo";
import {
  formatMillions,
  formatMultiple,
  formatIRR,
} from "../../utils/formatting";
import type { LBOInputs } from "../../types/fund";

const DEFAULT_LBO: LBOInputs = {
  entryEBITDA: 50,
  entryMultiple: 12,
  debtPercent: 0.6,
  interestRate: 0.075,
  ebitdaGrowthRate: 0.1,
  exitMultiple: 14,
  holdYears: 5,
  fcfConversion: 0.55,
  mandatoryAmortization: 0.05,
};

const EXIT_MULTS = [8, 10, 12, 14, 16, 18, 20];
const GROWTH_RATES = [-0.05, 0, 0.05, 0.1, 0.15, 0.2];

function moicColor(moic: number): string {
  if (moic >= 3) return "#34D399";
  if (moic >= 2) return "#818CF8";
  if (moic >= 1.5) return "#FCD34D";
  if (moic >= 1) return "#9CA3AF";
  return "#F87171";
}

function irrColor(irr: number | null): string {
  if (irr === null) return "#6B7280";
  if (irr >= 0.25) return "#34D399";
  if (irr >= 0.2) return "#818CF8";
  if (irr >= 0.15) return "#FCD34D";
  if (irr >= 0.1) return "#9CA3AF";
  return "#F87171";
}

function fmtIRR(irr: number | null): string {
  if (irr === null || !isFinite(irr)) return "N/A";
  return `${(irr * 100).toFixed(1)}%`;
}

export function LBOTab() {
  const [lbo, setLBO] = useState<LBOInputs>(DEFAULT_LBO);

  const result = useMemo(() => calculateLBO(lbo), [lbo]);

  const set = <K extends keyof LBOInputs>(k: K, v: LBOInputs[K]) =>
    setLBO((prev) => ({ ...prev, [k]: v }));

  const vc = result.valueCreation;
  const vcTotal =
    Math.abs(vc.ebitdaGrowth) +
    Math.abs(vc.multipleExpansion) +
    Math.abs(vc.debtPaydown);

  // Equity bridge waterfall data for BarChart
  const bridgeData = [
    {
      name: "Entry\nEquity",
      value: result.entryEquity,
      fill: "#6B7280",
      base: 0,
    },
    {
      name: "EBITDA\nGrowth",
      value: Math.abs(vc.ebitdaGrowth),
      fill: vc.ebitdaGrowth >= 0 ? "#34D399" : "#F87171",
      base: result.entryEquity,
    },
    {
      name: "Multiple\nExpansion",
      value: Math.abs(vc.multipleExpansion),
      fill: vc.multipleExpansion >= 0 ? "#818CF8" : "#F87171",
      base:
        result.entryEquity +
        (vc.ebitdaGrowth >= 0 ? vc.ebitdaGrowth : -Math.abs(vc.ebitdaGrowth)),
    },
    {
      name: "Debt\nPaydown",
      value: Math.abs(vc.debtPaydown),
      fill: vc.debtPaydown >= 0 ? "#6EE7B7" : "#F87171",
      base:
        result.entryEquity +
        (vc.ebitdaGrowth >= 0 ? vc.ebitdaGrowth : -Math.abs(vc.ebitdaGrowth)) +
        (vc.multipleExpansion >= 0
          ? vc.multipleExpansion
          : -Math.abs(vc.multipleExpansion)),
    },
    {
      name: "Exit\nEquity",
      value: result.exitEquity,
      fill: "#F59E0B",
      base: 0,
    },
  ];

  return (
    <div className="max-w-7xl mx-auto px-6 py-8 space-y-6">
      {/* Educational callout */}
      <div
        className="flex gap-3 p-4 rounded-xl"
        style={{
          background: "rgba(245,158,11,0.08)",
          border: "1px solid rgba(245,158,11,0.2)",
        }}
      >
        <Info
          size={16}
          className="flex-shrink-0 mt-0.5"
          style={{ color: "#F59E0B" }}
        />
        <div className="text-sm text-[#9CA3AF] leading-relaxed">
          <strong style={{ color: "#F59E0B" }}>Leveraged Buyout (LBO)</strong>{" "}
          returns come from three sources:{" "}
          <Tooltip
            term="EBITDA Growth"
            definition="Organic revenue growth and/or margin expansion increase earnings, which drive a higher EV at exit"
          >
            EBITDA growth
          </Tooltip>
          ,{" "}
          <Tooltip
            term="Multiple Expansion"
            definition="Exiting at a higher EV/EBITDA multiple than the entry multiple (market re-rating, improved business quality)"
          >
            multiple expansion
          </Tooltip>
          , and{" "}
          <Tooltip
            term="Debt Paydown"
            definition="Free cash flow generated by the business reduces debt, converting enterprise value to equity value"
          >
            debt paydown
          </Tooltip>
          . High leverage amplifies equity returns but increases default risk if
          EBITDA declines.
        </div>
      </div>

      {/* Entry Parameters */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div
          className="rounded-xl p-5"
          style={{ background: "#111827", border: "1px solid #374151" }}
        >
          <h3 className="text-sm font-semibold text-[#F9FAFB] mb-4">
            Entry & Structure
          </h3>
          <div className="grid grid-cols-2 gap-6">
            <Slider
              label="Entry EBITDA"
              value={lbo.entryEBITDA}
              min={5}
              max={500}
              step={5}
              format={(v) => formatMillions(v)}
              onChange={(v) => set("entryEBITDA", v)}
            />
            <Slider
              label="Entry EV/EBITDA"
              value={lbo.entryMultiple}
              min={4}
              max={25}
              step={0.5}
              format={(v) => `${v.toFixed(1)}x`}
              onChange={(v) => set("entryMultiple", v)}
            />
            <Slider
              label="Debt / EV"
              value={lbo.debtPercent * 100}
              min={20}
              max={80}
              step={5}
              format={(v) => `${v.toFixed(0)}%`}
              onChange={(v) => set("debtPercent", v / 100)}
            />
            <Slider
              label="Interest Rate"
              value={lbo.interestRate * 100}
              min={3}
              max={15}
              step={0.25}
              format={(v) => `${v.toFixed(2)}%`}
              onChange={(v) => set("interestRate", v / 100)}
            />
            <Slider
              label="Mandatory Amort"
              value={lbo.mandatoryAmortization * 100}
              min={0}
              max={20}
              step={1}
              format={(v) => `${v.toFixed(0)}% / yr`}
              onChange={(v) => set("mandatoryAmortization", v / 100)}
            />
            <Slider
              label="FCF Conversion"
              value={lbo.fcfConversion * 100}
              min={20}
              max={90}
              step={5}
              format={(v) => `${v.toFixed(0)}%`}
              onChange={(v) => set("fcfConversion", v / 100)}
            />
          </div>
        </div>

        <div
          className="rounded-xl p-5"
          style={{ background: "#111827", border: "1px solid #374151" }}
        >
          <h3 className="text-sm font-semibold text-[#F9FAFB] mb-4">
            Exit Assumptions
          </h3>
          <div className="grid grid-cols-2 gap-6">
            <Slider
              label="EBITDA Growth / yr"
              value={lbo.ebitdaGrowthRate * 100}
              min={-10}
              max={30}
              step={1}
              format={(v) => `${v.toFixed(0)}%`}
              onChange={(v) => set("ebitdaGrowthRate", v / 100)}
            />
            <Slider
              label="Exit EV/EBITDA"
              value={lbo.exitMultiple}
              min={4}
              max={25}
              step={0.5}
              format={(v) => `${v.toFixed(1)}x`}
              onChange={(v) => set("exitMultiple", v)}
            />
            <Slider
              label="Hold Period"
              value={lbo.holdYears}
              min={2}
              max={10}
              step={1}
              format={(v) => `${v} yr`}
              onChange={(v) => set("holdYears", v)}
            />
          </div>

          {/* Entry vs Exit summary */}
          <div className="mt-5 grid grid-cols-2 gap-3">
            {[
              {
                label: "Entry EV",
                value: formatMillions(result.entryEV),
                sub: `${lbo.entryMultiple.toFixed(1)}x EBITDA`,
                color: "#6B7280",
              },
              {
                label: "Exit EV",
                value: formatMillions(result.exitEV),
                sub: `${lbo.exitMultiple.toFixed(1)}x EBITDA`,
                color: "#34D399",
              },
              {
                label: "Entry Equity",
                value: formatMillions(result.entryEquity),
                sub: `${((1 - lbo.debtPercent) * 100).toFixed(0)}% of EV`,
                color: "#818CF8",
              },
              {
                label: "Exit Equity",
                value: formatMillions(result.exitEquity),
                sub: `After debt repayment`,
                color: "#6EE7B7",
              },
            ].map((item) => (
              <div
                key={item.label}
                className="rounded-lg p-3"
                style={{ background: "#0A0F1C", border: "1px solid #1F2937" }}
              >
                <div className="text-xs" style={{ color: "#6B7280" }}>
                  {item.label}
                </div>
                <div
                  className="text-base font-bold mt-0.5"
                  style={{ color: item.color }}
                >
                  {item.value}
                </div>
                <div className="text-xs mt-0.5" style={{ color: "#4B5563" }}>
                  {item.sub}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Key Stats Cards */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
        {[
          {
            label: "Entry EV",
            value: formatMillions(result.entryEV),
            sub: `${lbo.entryMultiple.toFixed(1)}x EBITDA`,
            color: "#9CA3AF",
          },
          {
            label: "Exit EV",
            value: formatMillions(result.exitEV),
            sub: `${lbo.exitMultiple.toFixed(1)}x EBITDA`,
            color: "#34D399",
          },
          {
            label: "Entry Equity",
            value: formatMillions(result.entryEquity),
            sub: `${((1 - lbo.debtPercent) * 100).toFixed(0)}% of EV`,
            color: "#818CF8",
          },
          {
            label: "Exit Equity",
            value: formatMillions(result.exitEquity),
            sub: "After debt repayment",
            color: "#6EE7B7",
          },
          {
            label: "Gross MOIC",
            value: formatMultiple(result.grossMOIC),
            sub: `${lbo.holdYears}-yr hold`,
            color: moicColor(result.grossMOIC),
          },
          {
            label: "Gross IRR",
            value: formatIRR(result.grossIRR),
            sub: "Annualized return",
            color: irrColor(result.grossIRR),
          },
        ].map((item) => (
          <div
            key={item.label}
            className="rounded-xl p-4"
            style={{ background: "#111827", border: "1px solid #374151" }}
          >
            <div className="text-xs mb-1" style={{ color: "#6B7280" }}>
              {item.label}
            </div>
            <div className="text-lg font-bold" style={{ color: item.color }}>
              {item.value}
            </div>
            <div className="text-xs mt-0.5" style={{ color: "#4B5563" }}>
              {item.sub}
            </div>
          </div>
        ))}
      </div>

      {/* Key Metrics */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <MetricCard
          label="Gross MOIC"
          value={formatMultiple(result.grossMOIC)}
          status={
            result.grossMOIC >= 3
              ? "positive"
              : result.grossMOIC >= 2
                ? "neutral"
                : "negative"
          }
          description={`${lbo.holdYears}-year hold`}
        />
        <MetricCard
          label="Gross IRR"
          value={formatIRR(result.grossIRR)}
          status={
            result.grossIRR !== null && result.grossIRR > 0.2
              ? "positive"
              : result.grossIRR !== null && result.grossIRR > 0.12
                ? "neutral"
                : "negative"
          }
          description="Annualized equity return"
        />
        <MetricCard
          label="Entry Debt / EBITDA"
          value={`${(result.entryDebt / lbo.entryEBITDA).toFixed(1)}x`}
          status={
            result.entryDebt / lbo.entryEBITDA <= 5
              ? "positive"
              : result.entryDebt / lbo.entryEBITDA <= 7
                ? "neutral"
                : "negative"
          }
          description="Leverage at close"
        />
        <MetricCard
          label="Exit Debt / EBITDA"
          value={`${result.debtSchedule.find((d) => d.year === lbo.holdYears)?.debtToEBITDA.toFixed(1) ?? "—"}x`}
          status="positive"
          description="Leverage at exit"
        />
      </div>

      {/* Scenario Analysis — Bull / Base / Bear */}
      <div
        className="rounded-xl p-5"
        style={{ background: "#111827", border: "1px solid #374151" }}
      >
        <h3 className="text-sm font-semibold text-[#F9FAFB] mb-1">
          EBITDA Growth Scenarios
        </h3>
        <p className="text-xs text-[#6B7280] mb-4">
          Bull (+5%), Base, Bear (-5%) EBITDA growth — debt sweep runs
          independently for each
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {(
            [
              {
                key: "bear" as const,
                label: "Bear Case",
                icon: "▼",
                color: "#F87171",
                bg: "rgba(248,113,113,0.07)",
              },
              {
                key: "base" as const,
                label: "Base Case",
                icon: "●",
                color: "#F59E0B",
                bg: "rgba(245,158,11,0.07)",
              },
              {
                key: "bull" as const,
                label: "Bull Case",
                icon: "▲",
                color: "#34D399",
                bg: "rgba(52,211,153,0.07)",
              },
            ] as const
          ).map(({ key, label, icon, color, bg }) => {
            const s = result.scenarios[key];
            return (
              <div
                key={key}
                className="rounded-lg p-4"
                style={{ background: bg, border: `1px solid ${color}30` }}
              >
                <div className="flex items-center gap-2 mb-3">
                  <span className="font-bold text-sm" style={{ color }}>
                    {icon} {label}
                  </span>
                  <span
                    className="text-xs font-mono"
                    style={{ color: "#6B7280" }}
                  >
                    {(s.growthRate * 100).toFixed(0)}% EBITDA/yr
                  </span>
                </div>
                <div className="grid grid-cols-2 gap-3">
                  {[
                    { l: "Exit EBITDA", v: formatMillions(s.exitEBITDA) },
                    { l: "Exit EV", v: formatMillions(s.exitEV) },
                    { l: "Exit Equity", v: formatMillions(s.exitEquity) },
                    { l: "MOIC", v: formatMultiple(s.moic) },
                    { l: "IRR", v: fmtIRR(s.irr) },
                  ].map(({ l, v }) => (
                    <div key={l}>
                      <div className="text-xs" style={{ color: "#6B7280" }}>
                        {l}
                      </div>
                      <div className="text-sm font-semibold" style={{ color }}>
                        {v}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Equity Bridge Waterfall Chart */}
      <div
        className="rounded-xl p-5"
        style={{ background: "#111827", border: "1px solid #374151" }}
      >
        <h3 className="text-sm font-semibold text-[#F9FAFB] mb-1">
          Equity Value Bridge — Waterfall
        </h3>
        <p className="text-xs text-[#6B7280] mb-4">
          From entry equity to exit equity: EBITDA growth, multiple expansion,
          and debt paydown contributions
        </p>
        <ResponsiveContainer width="100%" height={220}>
          <BarChart
            data={bridgeData}
            margin={{ top: 10, right: 20, left: 10, bottom: 5 }}
          >
            <CartesianGrid
              strokeDasharray="3 3"
              stroke="#1F2937"
              vertical={false}
            />
            <XAxis
              dataKey="name"
              tick={{ fill: "#9CA3AF", fontSize: 11 }}
              axisLine={{ stroke: "#374151" }}
              tickLine={false}
            />
            <YAxis
              tick={{ fill: "#6B7280", fontSize: 10 }}
              axisLine={false}
              tickLine={false}
              tickFormatter={(v) => formatMillions(v)}
            />
            <RechartTooltip
              contentStyle={{
                background: "#1F2937",
                border: "1px solid #374151",
                borderRadius: 8,
                color: "#F9FAFB",
                fontSize: 12,
              }}
              // eslint-disable-next-line @typescript-eslint/no-explicit-any
              formatter={(value: any, _name: any, props: any) => [
                formatMillions(typeof value === "number" ? value : 0),
                props.payload?.fill === "#6B7280" ||
                props.payload?.fill === "#F59E0B"
                  ? "Equity Value"
                  : "Contribution",
              ]}
            />
            {/* Invisible base bar for waterfall offset */}
            <Bar dataKey="base" stackId="w" fill="transparent" />
            <Bar dataKey="value" stackId="w" radius={[4, 4, 0, 0]}>
              {bridgeData.map((entry, idx) => (
                <Cell key={idx} fill={entry.fill} />
              ))}
            </Bar>
            <ReferenceLine y={0} stroke="#374151" />
          </BarChart>
        </ResponsiveContainer>
        <div className="flex gap-4 mt-2 text-xs flex-wrap">
          {[
            { color: "#6B7280", label: "Entry/Exit Equity" },
            { color: "#34D399", label: "EBITDA Growth" },
            { color: "#818CF8", label: "Multiple Expansion" },
            { color: "#6EE7B7", label: "Debt Paydown" },
            { color: "#F87171", label: "Negative contribution" },
          ].map((item) => (
            <span
              key={item.label}
              className="flex items-center gap-1"
              style={{ color: "#6B7280" }}
            >
              <span
                style={{
                  width: 8,
                  height: 8,
                  borderRadius: 2,
                  background: item.color,
                  display: "inline-block",
                }}
              />
              {item.label}
            </span>
          ))}
        </div>
      </div>

      {/* Value Creation Bridge */}
      <div
        className="rounded-xl p-5"
        style={{ background: "#111827", border: "1px solid #374151" }}
      >
        <h3 className="text-sm font-semibold text-[#F9FAFB] mb-1">
          Value Creation Bridge
        </h3>
        <p className="text-xs text-[#6B7280] mb-4">
          Equity gain of {formatMillions(vc.total)} broken down by source
        </p>
        <div className="space-y-3">
          {[
            {
              label: "EBITDA Growth",
              value: vc.ebitdaGrowth,
              color: "#34D399",
              description: `Earnings grew from ${formatMillions(lbo.entryEBITDA)} to ${formatMillions(lbo.entryEBITDA * Math.pow(1 + lbo.ebitdaGrowthRate, lbo.holdYears))} at entry multiple`,
            },
            {
              label: "Multiple Expansion",
              value: vc.multipleExpansion,
              color: "#818CF8",
              description: `Exit at ${lbo.exitMultiple.toFixed(1)}x vs entry at ${lbo.entryMultiple.toFixed(1)}x`,
            },
            {
              label: "Debt Paydown",
              value: vc.debtPaydown,
              color: "#6EE7B7",
              description: `Debt reduced from ${formatMillions(result.entryDebt)} to ${formatMillions(result.exitDebt)}`,
            },
          ].map((item) => {
            const pct = vcTotal > 0 ? Math.abs(item.value) / vcTotal : 0;
            const isNeg = item.value < 0;
            return (
              <div key={item.label} className="space-y-1">
                <div className="flex justify-between items-center text-xs">
                  <div>
                    <span
                      style={{
                        color: isNeg ? "#F87171" : item.color,
                        fontWeight: 600,
                      }}
                    >
                      {item.label}
                    </span>
                    <span className="ml-2" style={{ color: "#4B5563" }}>
                      {item.description}
                    </span>
                  </div>
                  <span
                    style={{
                      color: isNeg ? "#F87171" : item.color,
                      fontWeight: 700,
                    }}
                  >
                    {isNeg ? "-" : "+"}
                    {formatMillions(Math.abs(item.value))}
                  </span>
                </div>
                <div
                  className="w-full rounded-full h-2.5"
                  style={{ background: "#1F2937" }}
                >
                  <div
                    className="h-2.5 rounded-full transition-all duration-500"
                    style={{
                      width: `${pct * 100}%`,
                      background: isNeg ? "#F87171" : item.color,
                    }}
                  />
                </div>
                <div className="text-xs" style={{ color: "#4B5563" }}>
                  {(pct * 100).toFixed(0)}% of total value creation
                </div>
              </div>
            );
          })}
        </div>

        {/* Bridge totals */}
        <div className="mt-4 pt-4 border-t border-[#1F2937] flex justify-between text-sm">
          <span style={{ color: "#9CA3AF" }}>Entry Equity</span>
          <span style={{ color: "#6B7280" }}>
            {formatMillions(result.entryEquity)}
          </span>
        </div>
        <div className="flex justify-between text-sm">
          <span style={{ color: "#9CA3AF" }}>+ Value Created</span>
          <span style={{ color: "#34D399" }}>+{formatMillions(vc.total)}</span>
        </div>
        <div className="flex justify-between text-sm font-bold border-t border-[#374151] pt-2 mt-1">
          <span style={{ color: "#F9FAFB" }}>= Exit Equity</span>
          <span style={{ color: "#34D399" }}>
            {formatMillions(result.exitEquity)}
          </span>
        </div>
      </div>

      {/* Debt Schedule */}
      <div
        className="rounded-xl p-5"
        style={{ background: "#111827", border: "1px solid #374151" }}
      >
        <h3 className="text-sm font-semibold text-[#F9FAFB] mb-4">
          Debt Amortization Schedule
        </h3>
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr style={{ borderBottom: "1px solid #374151" }}>
                {[
                  "Year",
                  "Beg. Debt",
                  "EBITDA",
                  "FCF",
                  "Interest",
                  "Amortization",
                  "End Debt",
                  "D/EBITDA",
                  "DSCR",
                  "Equity",
                  "MOIC",
                ].map((h) => (
                  <th
                    key={h}
                    className="pb-2 text-right first:text-left"
                    style={{
                      color: "#6B7280",
                      fontWeight: 600,
                      paddingRight: 12,
                    }}
                  >
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {result.debtSchedule.slice(0, lbo.holdYears).map((row) => (
                <tr
                  key={row.year}
                  style={{ borderBottom: "1px solid #1F2937" }}
                >
                  {[
                    { v: `Year ${row.year}`, left: true },
                    { v: formatMillions(row.beginningDebt) },
                    { v: formatMillions(row.ebitda) },
                    { v: formatMillions(row.fcf), color: "#60A5FA" },
                    {
                      v: `(${formatMillions(row.interest)})`,
                      color: "#F87171",
                    },
                    {
                      v: `(${formatMillions(row.amortization)})`,
                      color: "#FCD34D",
                    },
                    { v: formatMillions(row.endingDebt) },
                    {
                      v: `${row.debtToEBITDA.toFixed(1)}x`,
                      color:
                        row.debtToEBITDA <= 5
                          ? "#34D399"
                          : row.debtToEBITDA <= 7
                            ? "#FCD34D"
                            : "#F87171",
                    },
                    {
                      v: row.dscr >= 99 ? "—" : `${row.dscr.toFixed(2)}x`,
                      color:
                        row.dscr >= 1.5
                          ? "#34D399"
                          : row.dscr >= 1.2
                            ? "#FCD34D"
                            : "#F87171",
                    },
                    { v: formatMillions(row.equity), color: "#818CF8" },
                    {
                      v: `${row.moic.toFixed(2)}x`,
                      color: moicColor(row.moic),
                    },
                  ].map((cell, ci) => (
                    <td
                      key={ci}
                      className={`py-2 ${cell.left ? "text-left" : "text-right"}`}
                      style={{
                        color: cell.color ?? "#D1D5DB",
                        paddingRight: 12,
                      }}
                    >
                      {cell.v}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Sensitivity Table */}
      <div
        className="rounded-xl p-5"
        style={{ background: "#111827", border: "1px solid #374151" }}
      >
        <h3 className="text-sm font-semibold text-[#F9FAFB] mb-1">
          MOIC Sensitivity
        </h3>
        <p className="text-xs text-[#6B7280] mb-4">
          Exit multiple (rows) × EBITDA growth rate (columns) — hold period:{" "}
          {lbo.holdYears} years
        </p>
        <div className="overflow-x-auto">
          <table className="text-xs">
            <thead>
              <tr>
                <th
                  className="pb-2 pr-3 text-left"
                  style={{ color: "#6B7280" }}
                >
                  Exit × \ Growth
                </th>
                {GROWTH_RATES.map((gr) => (
                  <th
                    key={gr}
                    className="pb-2 px-3 text-center"
                    style={{ color: "#6B7280" }}
                  >
                    {(gr * 100).toFixed(0)}%
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {EXIT_MULTS.map((em) => (
                <tr key={em}>
                  <td
                    className="py-1.5 pr-3 font-semibold"
                    style={{ color: "#9CA3AF" }}
                  >
                    {em}x
                  </td>
                  {GROWTH_RATES.map((gr) => {
                    const cell = result.sensitivityGrid.find(
                      (c) =>
                        c.exitMult === em &&
                        Math.abs(c.growthRate - gr) < 0.001,
                    );
                    const m = cell?.moic ?? 0;
                    const isTarget =
                      em === lbo.exitMultiple &&
                      Math.abs(gr - lbo.ebitdaGrowthRate) < 0.001;
                    return (
                      <td
                        key={gr}
                        className="py-1.5 px-3 text-center rounded"
                        style={{
                          color: moicColor(m),
                          fontWeight: isTarget ? 800 : 500,
                          background: isTarget
                            ? "rgba(99,102,241,0.15)"
                            : "transparent",
                          border: isTarget
                            ? "1px solid rgba(99,102,241,0.4)"
                            : "1px solid transparent",
                        }}
                      >
                        {m.toFixed(2)}x
                      </td>
                    );
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="mt-3 flex gap-4 text-xs">
          {[
            { color: "#34D399", label: "≥3x" },
            { color: "#818CF8", label: "2–3x" },
            { color: "#FCD34D", label: "1.5–2x" },
            { color: "#9CA3AF", label: "1–1.5x" },
            { color: "#F87171", label: "<1x (loss)" },
          ].map((item) => (
            <span
              key={item.label}
              className="flex items-center gap-1"
              style={{ color: item.color }}
            >
              <span
                style={{
                  width: 8,
                  height: 8,
                  borderRadius: 2,
                  background: item.color,
                  display: "inline-block",
                }}
              />
              {item.label}
            </span>
          ))}
        </div>
      </div>

      {/* Entry Multiple × Exit Multiple → IRR Sensitivity Heatmap */}
      <div
        className="rounded-xl p-5"
        style={{ background: "#111827", border: "1px solid #374151" }}
      >
        <h3 className="text-sm font-semibold text-[#F9FAFB] mb-1">
          IRR Sensitivity: Entry Multiple × Exit Multiple
        </h3>
        <p className="text-xs text-[#6B7280] mb-4">
          Gross IRR (%) across entry and exit EV/EBITDA multiples — hold period:{" "}
          {lbo.holdYears} years, EBITDA growth:{" "}
          {(lbo.ebitdaGrowthRate * 100).toFixed(0)}%/yr
        </p>
        <div className="overflow-x-auto">
          <table className="text-xs">
            <thead>
              <tr>
                <th
                  className="pb-2 pr-4 text-left"
                  style={{ color: "#6B7280", minWidth: 80 }}
                >
                  Entry × \ Exit ×
                </th>
                {result.exitMultiples.map((xm) => (
                  <th
                    key={xm}
                    className="pb-2 px-3 text-center"
                    style={{ color: "#6B7280", minWidth: 64 }}
                  >
                    {xm.toFixed(1)}x
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {result.entryExitSensitivity.map((row) => (
                <tr key={row.entryMult}>
                  <td
                    className="py-1.5 pr-4 font-semibold"
                    style={{ color: "#9CA3AF" }}
                  >
                    {row.entryMult.toFixed(1)}x
                  </td>
                  {row.irrs.map(({ exitMult, irr }) => {
                    const isBase =
                      Math.abs(row.entryMult - lbo.entryMultiple) < 0.01 &&
                      Math.abs(exitMult - lbo.exitMultiple) < 0.01;
                    return (
                      <td
                        key={exitMult}
                        className="py-1.5 px-3 text-center rounded"
                        style={{
                          color: irrColor(irr),
                          fontWeight: isBase ? 800 : 500,
                          background: isBase
                            ? "rgba(99,102,241,0.15)"
                            : "transparent",
                          border: isBase
                            ? "1px solid rgba(99,102,241,0.4)"
                            : "1px solid transparent",
                        }}
                      >
                        {fmtIRR(irr)}
                      </td>
                    );
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="mt-3 flex gap-4 text-xs">
          {[
            { color: "#34D399", label: "≥25% IRR" },
            { color: "#818CF8", label: "20–25%" },
            { color: "#FCD34D", label: "15–20%" },
            { color: "#9CA3AF", label: "10–15%" },
            { color: "#F87171", label: "<10%" },
          ].map((item) => (
            <span
              key={item.label}
              className="flex items-center gap-1"
              style={{ color: item.color }}
            >
              <span
                style={{
                  width: 8,
                  height: 8,
                  borderRadius: 2,
                  background: item.color,
                  display: "inline-block",
                }}
              />
              {item.label}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}
