import type { EventCode, EventConfig } from "../types/decaTypes";

export const EVENT_CONFIG: Record<EventCode, EventConfig> = {
  EIB: {
    code: "EIB",
    name: "Independent Business Plan",
    format: "written",
    pageLimit: 20,
    financialPointsWritten: 10,
    financialPointsPresentation: 5,
    totalPoints: 100,
    steps: {
      businessOverview: "required",
      assumptions: "required",
      startupCosts: "required",
      incomeStatement: "required",
      cashFlow: "required",
      balanceSheet: "required",
      threeYearPlan: "required",
      capitalNeeds: "required",
      breakEven: "recommended",
      sensitivity: "recommended",
      implementationBudget: "hidden",
      internationalFinance: "hidden",
      currentFinancials: "hidden",
    },
    rubricNotes:
      "Section IX (Detailed Financials) is worth 10 of 60 written points — the single highest-weighted criterion in the entire rubric. Judges play loan officers or VCs. Every number must be internally consistent and sourced.",
    description:
      "Most financially demanding event. Full income statement, cash flow, balance sheet, 3-year plan.",
  },
  IBP: {
    code: "IBP",
    name: "International Business Plan",
    format: "written",
    pageLimit: 20,
    financialPointsWritten: 5,
    financialPointsPresentation: 5,
    totalPoints: 100,
    steps: {
      businessOverview: "required",
      assumptions: "required",
      startupCosts: "required",
      incomeStatement: "required",
      cashFlow: "required",
      balanceSheet: "required",
      threeYearPlan: "required",
      capitalNeeds: "required",
      breakEven: "recommended",
      sensitivity: "recommended",
      implementationBudget: "hidden",
      internationalFinance: "required",
      currentFinancials: "hidden",
    },
    rubricNotes:
      "IBP trades 5 points from Detailed Financials to Cost Structure and International Analysis. Include currency conversion, tariff modeling, and trade document costs.",
    description:
      "Same as EIB plus international financial analysis and FX considerations.",
  },
  EFB: {
    code: "EFB",
    name: "Franchise Business Plan",
    format: "written",
    pageLimit: 20,
    financialPointsWritten: 8,
    financialPointsPresentation: 4,
    totalPoints: 100,
    steps: {
      businessOverview: "required",
      assumptions: "required",
      startupCosts: "required",
      incomeStatement: "required",
      cashFlow: "required",
      balanceSheet: "hidden",
      threeYearPlan: "hidden",
      capitalNeeds: "required",
      breakEven: "recommended",
      sensitivity: "hidden",
      implementationBudget: "hidden",
      internationalFinance: "hidden",
      currentFinancials: "hidden",
    },
    rubricNotes:
      "EFB uses 'Operating Statement' not 'Income Statement'. Requires 2-year annual projections and 1-year cash flow. Include franchise fees, royalties, and required supplier costs.",
    description:
      "Franchise-specific financials. 2-year operating statement, 1-year cash flow.",
  },
  EBG: {
    code: "EBG",
    name: "Business Growth Plan",
    format: "written",
    pageLimit: 20,
    financialPointsWritten: 12,
    financialPointsPresentation: 0,
    totalPoints: 100,
    steps: {
      businessOverview: "required",
      assumptions: "hidden",
      startupCosts: "hidden",
      incomeStatement: "hidden",
      cashFlow: "hidden",
      balanceSheet: "hidden",
      threeYearPlan: "hidden",
      capitalNeeds: "required",
      breakEven: "hidden",
      sensitivity: "hidden",
      implementationBudget: "hidden",
      internationalFinance: "hidden",
      currentFinancials: "required",
    },
    rubricNotes:
      "EBG requires REAL financial documents from an existing student-owned business. Focus on current financial reality and expansion capital. Financial section worth 12 of 60 written points (4 criteria × 3 pts each).",
    description:
      "Real existing business. Current financials + expansion capital plan.",
  },
  ESB: {
    code: "ESB",
    name: "Start-Up Business Plan",
    format: "pitchdeck",
    pageLimit: 20,
    financialPointsWritten: 9,
    financialPointsPresentation: 9,
    totalPoints: 100,
    steps: {
      businessOverview: "required",
      assumptions: "recommended",
      startupCosts: "recommended",
      incomeStatement: "hidden",
      cashFlow: "hidden",
      balanceSheet: "hidden",
      threeYearPlan: "hidden",
      capitalNeeds: "required",
      breakEven: "hidden",
      sensitivity: "hidden",
      implementationBudget: "hidden",
      internationalFinance: "hidden",
      currentFinancials: "hidden",
    },
    rubricNotes:
      "ESB is now a 20-slide pitch deck (2025–26). Revenue Streams (9 pts) and Cost Structure (9 pts) are embedded in slides, not formal statements. Focus on gross margin, customer acquisition cost, and lifetime value.",
    description:
      "Revenue model + cost structure. No formal statements required.",
  },
  EIP: {
    code: "EIP",
    name: "Innovation Plan",
    format: "pitchdeck",
    pageLimit: 20,
    financialPointsWritten: 0,
    financialPointsPresentation: 0,
    totalPoints: 100,
    steps: {
      businessOverview: "required",
      assumptions: "hidden",
      startupCosts: "hidden",
      incomeStatement: "hidden",
      cashFlow: "hidden",
      balanceSheet: "hidden",
      threeYearPlan: "hidden",
      capitalNeeds: "hidden",
      breakEven: "hidden",
      sensitivity: "hidden",
      implementationBudget: "hidden",
      internationalFinance: "hidden",
      currentFinancials: "hidden",
    },
    rubricNotes:
      "EIP requires NO financial statements. Feasibility is assessed in the Conclusion (14 pts). Provide only a brief financial viability summary.",
    description: "Feasibility summary only. Minimal financials.",
  },
  BOR: {
    code: "BOR",
    name: "Business Operations Research",
    format: "written",
    pageLimit: 20,
    financialPointsWritten: 4,
    financialPointsPresentation: 6,
    totalPoints: 100,
    steps: {
      businessOverview: "required",
      assumptions: "hidden",
      startupCosts: "hidden",
      incomeStatement: "hidden",
      cashFlow: "hidden",
      balanceSheet: "hidden",
      threeYearPlan: "hidden",
      capitalNeeds: "hidden",
      breakEven: "hidden",
      sensitivity: "hidden",
      implementationBudget: "required",
      internationalFinance: "hidden",
      currentFinancials: "hidden",
    },
    rubricNotes:
      "BOR/FOR require only a Proposed Budget — itemized costs per strategic activity. No income statements, cash flow, or balance sheets. Include anticipated ROI. Worth 10 of 100 total points.",
    description: "Implementation budget + ROI. No formal statements.",
  },
  FOR: {
    code: "FOR",
    name: "Finance Operations Research",
    format: "written",
    pageLimit: 20,
    financialPointsWritten: 4,
    financialPointsPresentation: 6,
    totalPoints: 100,
    steps: {
      businessOverview: "required",
      assumptions: "hidden",
      startupCosts: "hidden",
      incomeStatement: "hidden",
      cashFlow: "hidden",
      balanceSheet: "hidden",
      threeYearPlan: "hidden",
      capitalNeeds: "hidden",
      breakEven: "hidden",
      sensitivity: "hidden",
      implementationBudget: "required",
      internationalFinance: "hidden",
      currentFinancials: "hidden",
    },
    rubricNotes:
      "BOR/FOR require only a Proposed Budget — itemized costs per strategic activity. No income statements, cash flow, or balance sheets. Include anticipated ROI. Worth 10 of 100 total points.",
    description: "Same as BOR but finance-sector context.",
  },
  SMG: {
    code: "SMG",
    name: "Stock Market Game",
    format: "pitchdeck",
    pageLimit: 20,
    financialPointsWritten: 76,
    financialPointsPresentation: 0,
    totalPoints: 100,
    steps: {
      businessOverview: "hidden",
      assumptions: "hidden",
      startupCosts: "hidden",
      incomeStatement: "hidden",
      cashFlow: "hidden",
      balanceSheet: "hidden",
      threeYearPlan: "hidden",
      capitalNeeds: "hidden",
      breakEven: "hidden",
      sensitivity: "hidden",
      implementationBudget: "hidden",
      internationalFinance: "hidden",
      currentFinancials: "hidden",
    },
    rubricNotes:
      "SMG is portfolio-focused. Financial analysis accounts for ~76 of 100 points. Cover investment objectives, diversification strategy, research methodology, and future strategy changes.",
    description: "Investment portfolio analysis. Finance-heavy.",
  },
};

export const STEP_LABELS: Record<number, string> = {
  0: "Event",
  1: "Business",
  2: "Assumptions",
  3: "Startup Costs",
  4: "Income Statement",
  5: "Cash Flow",
  6: "Balance Sheet",
  7: "3-Year Plan",
  8: "Capital Needs",
  9: "Break-Even",
  10: "Sensitivity",
  11: "Impl. Budget",
  12: "International",
  13: "Current Financials",
  14: "Review",
};

// Returns array of step numbers visible for a given event
export function getVisibleSteps(eventCode: EventCode | null): number[] {
  if (!eventCode) return [0];

  const cfg = EVENT_CONFIG[eventCode];
  const stepMap: Record<number, keyof EventConfig["steps"]> = {
    1: "businessOverview",
    2: "assumptions",
    3: "startupCosts",
    4: "incomeStatement",
    5: "cashFlow",
    6: "balanceSheet",
    7: "threeYearPlan",
    8: "capitalNeeds",
    9: "breakEven",
    10: "sensitivity",
    11: "implementationBudget",
    12: "internationalFinance",
    13: "currentFinancials",
  };

  const visible = [0];
  for (const [stepNum, key] of Object.entries(stepMap)) {
    if (cfg.steps[key] !== "hidden") {
      visible.push(Number(stepNum));
    }
  }
  visible.push(14);
  return visible;
}
